# Generated by Django 6.0.5 on 2026-06-15 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaqCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faq_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OtpTokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(max_length=10)),
                ('pending_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_used', models.BooleanField()),
            ],
            options={
                'db_table': 'otp_tokens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'procedures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'requirements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.faqcategories')),
            ],
            options={
                'db_table': 'faqs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcedureDocuments',
            fields=[
                ('pk', models.CompositePrimaryKey('procedure_id', 'document_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.documents')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.offices')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.procedures')),
            ],
            options={
                'db_table': 'procedure_documents',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='faqcategories',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.procedures'),
        ),
        migrations.CreateModel(
            name='ProcedureRequirements',
            fields=[
                ('pk', models.CompositePrimaryKey('procedure_id', 'requirement_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.procedures')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.requirements')),
            ],
            options={
                'db_table': 'procedure_requirements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('id_number', models.BigIntegerField(unique=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('student_name', models.TextField(blank=True, null=True)),
                ('year_level', models.SmallIntegerField(blank=True, null=True)),
                ('program', models.TextField(blank=True, null=True)),
                ('auth_user', models.OneToOneField(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.offices')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.roles')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.procedures')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestDocuments',
            fields=[
                ('req_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.documents')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.requests')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'request_documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.requests')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'notifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcedureSteps',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('step_description', models.TextField()),
                ('person_in_charge', models.CharField(blank=True, max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_link', models.TextField(blank=True, null=True)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.procedures')),
            ],
            options={
                'db_table': 'procedure_steps',
                'managed': True,
                'unique_together': {('procedure', 'step_number')},
            },
        ),
    ]
