# Generated by Django 6.0.4 on 2026-07-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeProcedures',
            fields=[
                ('office_procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offices')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.procedures')),
            ],
            options={
                'db_table': 'office_procedures',
                'unique_together': {('office', 'procedure')},
            },
        ),
    ]
