# Generated by Django 6.0.4 on 2026-07-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_officeprocedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocuments',
            name='tracking_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
