# Generated by Django 6.0.4 on 2026-07-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requestdocuments_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduredocuments',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_documents', to='api.procedures'),
        ),
        migrations.AlterField(
            model_name='procedurerequirements',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_requirements', to='api.procedures'),
        ),
        migrations.AlterField(
            model_name='proceduresteps',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='api.procedures'),
        ),
    ]
