# Generated by Django 6.0.4 on 2026-07-09 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_proceduredocuments_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategories',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.procedures'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.procedures'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users'),
        ),
    ]
