# Generated by Django 6.0.4 on 2026-07-09 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_faqcategories_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.faqcategories'),
        ),
    ]
