# Generated by Django 6.0.4 on 2026-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_faqs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocuments',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
