# Generated by Django 6.0.4 on 2026-07-10 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_requestdocuments_reference_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceduredocuments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='procedurerequirements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requestdocuments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AddField(
            model_name='requestdocuments',
            name='document_name_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestdocuments',
            name='updated_by_id_snapshot',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='procedure_name_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='user_id_number_snapshot',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='officeprocedures',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offices'),
        ),
        migrations.AlterField(
            model_name='officeprocedures',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.procedures'),
        ),
        migrations.AlterField(
            model_name='proceduredocuments',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.documents'),
        ),
        migrations.AlterField(
            model_name='proceduredocuments',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.offices'),
        ),
        migrations.AlterField(
            model_name='procedurerequirements',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.requirements'),
        ),
        migrations.AlterField(
            model_name='requestdocuments',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.documents'),
        ),
        migrations.AlterField(
            model_name='requestdocuments',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.requests'),
        ),
        migrations.AlterField(
            model_name='requestdocuments',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestdocuments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requestdocuments',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.offices'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.roles'),
        ),
    ]
