# Generated by Django 6.0.4 on 2026-07-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_faqs_created_at_alter_faqs_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduredocuments',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documents'),
        ),
        migrations.AlterField(
            model_name='procedurerequirements',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirements'),
        ),
        migrations.AlterField(
            model_name='requestdocuments',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.documents'),
        ),
    ]
