# Generated by Django 6.0.4 on 2026-07-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_proceduredocuments_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='procedure',
            field=models.ForeignKey(db_column='procedure_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.procedures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirements',
            name='requirement_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ProcedureRequirements',
        ),
    ]
