# Generated by Django 6.0.4 on 2026-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_requirements_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocuments',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestdocuments',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
