# Generated by Django 6.0.4 on 2026-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_requestdocuments_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
